### PR TITLE
Add Symfony 5 support #SymfonyHackday

### PR DESCRIPTION
**Pull request by patrick-mota**
Add Symfony 5 support #SymfonyHackday

### CODE REVIEW

**Comment by mmoll** [comment]
@calbrecht Could you have look? :eyes:

I guess, we also can drop Symfony 2.x now.

**Comment by mmoll** [comment]
merged, merci @patrick-mota!

**Comment by garak** [comment]
A new release is needed.
Also, it would be nice to get a `branch-alias` to allow users to require unreleased versions without using `dev-master`

**Comment by mmoll** [comment]
2.2 got released. :package:

**Pull request merged**
